"""schema v3 baseline

Revision ID: 84e58e0eefae
Revises: 
Create Date: 2026-07-05 12:56:32.674410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84e58e0eefae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_result_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('media_hash', sa.String(length=64), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'media_hash')
    )
    op.create_table('forbidden_nicknames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forbidden_nicknames_word'), 'forbidden_nicknames', ['word'], unique=True)
    op.create_table('interest_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sa.String(length=12), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('ui_mode', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('stranger_requests_allowed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('mode_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('risk_score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_table('withdrawn_socials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawn_socials_provider'), 'withdrawn_socials', ['provider'], unique=False)
    op.create_index(op.f('ix_withdrawn_socials_provider_user_id'), 'withdrawn_socials', ['provider_user_id'], unique=False)
    op.create_table('blocks',
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_a', sa.Uuid(), nullable=True),
    sa.Column('user_b', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_a'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_b'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a', 'user_b')
    )
    op.create_index(op.f('ix_chat_rooms_user_a'), 'chat_rooms', ['user_a'], unique=False)
    op.create_index(op.f('ix_chat_rooms_user_b'), 'chat_rooms', ['user_b'], unique=False)
    op.create_table('friend_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_friend_requests_receiver_status', 'friend_requests', ['receiver_id', 'status'], unique=False)
    op.create_index(op.f('ix_friend_requests_sender_id'), 'friend_requests', ['sender_id'], unique=False)
    op.create_table('friendships',
    sa.Column('user_a', sa.Uuid(), nullable=False),
    sa.Column('user_b', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_a < user_b', name='ck_friendships_ordered'),
    sa.ForeignKeyConstraint(['user_a'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_a', 'user_b')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_table('send_restrictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_send_restrictions_pair', 'send_restrictions', ['sender_id', 'receiver_id', 'active'], unique=False)
    op.create_table('social_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id')
    )
    op.create_index(op.f('ix_social_identities_user_id'), 'social_identities', ['user_id'], unique=False)
    op.create_table('user_interest_tags',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['interest_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    op.create_table('user_mode_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('from_mode', sa.String(length=20), nullable=True),
    sa.Column('to_mode', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mode_history_user_id'), 'user_mode_history', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=10), server_default=sa.text("'text'"), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_status', sa.String(length=20), server_default=sa.text("'none'"), nullable=False),
    sa.Column('caption', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('caption_status', sa.String(length=20), server_default=sa.text("'none'"), nullable=False),
    sa.Column('safety_status', sa.String(length=20), nullable=False),
    sa.Column('revealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_room_created', 'chat_messages', ['room_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_safety_status'), 'chat_messages', ['safety_status'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_table('post_likes',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('post_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('uploader_id', sa.Uuid(), nullable=True),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('media_hash', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_status', sa.String(length=20), server_default=sa.text("'none'"), nullable=False),
    sa.Column('caption', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('caption_status', sa.String(length=20), server_default=sa.text("'none'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_media_media_hash'), 'post_media', ['media_hash'], unique=False)
    op.create_index(op.f('ix_post_media_post_id'), 'post_media', ['post_id'], unique=False)
    # ### end Alembic commands ###

    # ── 시드 ──────────────────────────────────────────────
    # TAG-01 관심사 태그 카탈로그 (명세 §6, 10 카테고리 43개)
    import uuid as _uuid

    tag_catalog = {
        "운동·건강": [("walking", "걷기"), ("hiking", "등산"), ("gym", "헬스"),
                    ("yoga", "요가"), ("cycling", "자전거"), ("home_training", "홈트")],
        "게임": [("mobile_game", "모바일게임"), ("pc_game", "PC게임"),
                ("board_game", "보드게임"), ("puzzle", "퍼즐")],
        "음악": [("listening_music", "음악 듣기"), ("singing", "노래"),
                ("instrument", "악기"), ("kpop", "K-pop"), ("trot", "트로트")],
        "영화·드라마": [("movie", "영화"), ("drama", "드라마"),
                      ("ott", "OTT"), ("animation", "애니메이션")],
        "책·글": [("reading", "독서"), ("webtoon", "웹툰"),
                 ("webnovel", "웹소설"), ("writing", "글쓰기")],
        "그림·만들기": [("drawing", "그림"), ("photo", "사진"),
                      ("craft_diy", "공예·DIY"), ("knitting", "뜨개")],
        "요리·먹기": [("cooking", "요리"), ("baking", "베이킹"), ("food_tour", "맛집"),
                    ("cafe", "카페"), ("dessert", "디저트")],
        "여행·나들이": [("domestic_travel", "국내여행"), ("camping", "캠핑"),
                      ("exhibition_museum", "전시·박물관"), ("driving", "드라이브")],
        "반려동물·자연": [("dog", "강아지"), ("cat", "고양이"), ("plant", "식물 키우기")],
        "일상·수다": [("daily_sharing", "일상 나누기"), ("small_talk", "소소한 대화"),
                    ("heart_sharing", "마음 나누기"), ("healing", "힐링")],
    }
    op.bulk_insert(
        sa.table(
            "interest_tags",
            sa.column("id", sa.Uuid),
            sa.column("code", sa.String),
            sa.column("category", sa.String),
            sa.column("label", sa.String),
        ),
        [
            {"id": _uuid.uuid4(), "code": code, "category": category, "label": label}
            for category, tags in tag_catalog.items()
            for code, label in tags
        ],
    )

    # ACC-01 닉네임 금칙어 (v2 시드 승계)
    seed_words = [
        "관리자", "운영자", "admin", "administrator", "운영팀", "시스템", "system",
        "씨발", "시발", "병신", "fuck", "shit", "bitch", "새끼", "지랄",
        "장애인비하", "애자", "병맛", "썅", "엿먹어", "꺼져", "죽어",
    ]
    op.bulk_insert(
        sa.table("forbidden_nicknames", sa.column("word", sa.String)),
        [{"word": w} for w in seed_words],
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_media_post_id'), table_name='post_media')
    op.drop_index(op.f('ix_post_media_media_hash'), table_name='post_media')
    op.drop_table('post_media')
    op.drop_table('post_likes')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_safety_status'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_room_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_user_mode_history_user_id'), table_name='user_mode_history')
    op.drop_table('user_mode_history')
    op.drop_table('user_interest_tags')
    op.drop_index(op.f('ix_social_identities_user_id'), table_name='social_identities')
    op.drop_table('social_identities')
    op.drop_index('ix_send_restrictions_pair', table_name='send_restrictions')
    op.drop_table('send_restrictions')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_requests_sender_id'), table_name='friend_requests')
    op.drop_index('ix_friend_requests_receiver_status', table_name='friend_requests')
    op.drop_table('friend_requests')
    op.drop_index(op.f('ix_chat_rooms_user_b'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_user_a'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_withdrawn_socials_provider_user_id'), table_name='withdrawn_socials')
    op.drop_index(op.f('ix_withdrawn_socials_provider'), table_name='withdrawn_socials')
    op.drop_table('withdrawn_socials')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_table('users')
    op.drop_table('interest_tags')
    op.drop_index(op.f('ix_forbidden_nicknames_word'), table_name='forbidden_nicknames')
    op.drop_table('forbidden_nicknames')
    op.drop_table('ai_result_cache')
    # ### end Alembic commands ###
